services:
  termin:
    depends_on:
      - grid
    build:
      context: .
      dockerfile: Dockerfile-dev
      args:
        - APP_ENV=development
    volumes:
      - .:/usr/src/app
    command: bash -c "bundle install && ruby app.rb"
    environment:
      - APP_ENV=development
      - TZ=Europe/Berlin
    stdin_open: true
    tty: true

  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
      args:
        - APP_ENV=development
    volumes:
      - .:/usr/src/app
    ports:
      - "5678:4567/tcp"
    command: bash -c "bundle install && ruby web.rb"
    environment:
      - APP_ENV=development
      - TZ=Europe/Berlin
    stdin_open: true
    tty: true

  grid:
    image: docker.io/selenium/standalone-chrome:latest
    shm_size: '2gb'
    ports:
      - "4445:4444/tcp"
      - "7901:7900/tcp"
