services:
  termin:
    depends_on:
      - grid
    build: .
    volumes:
      - .:/usr/src/app
    command: ruby app.rb
    stdin_open: true
    tty: true

  grid:
    image: docker.io/selenium/standalone-chrome:latest
    shm_size: '2gb'
    ports:
      - "4444:4444/tcp"
      - "7900:7900/tcp"
