services:
  runner:
    container_name: termin-runner-dev
    image: rcheung/termin_base:0.0.1-1-DEV
    restart: always
    command: bash -c "bundle install && rerun -b --ignore 'web/**/*' 'ruby app.rb'"
    depends_on:
      - grid
      - db
    build:
      context: .
      dockerfile: dev.Dockerfile
      args:
        - APP_ENV=development
    volumes:
      - .:/usr/src/app
    secrets:
      - postgres_passwd
      - telegram_token
    environment:
      APP_ENV: development
      TZ: Europe/Berlin
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_passwd
      POSTGRES_USER: termin
      TELEGRAM_TOKEN_FILE: /run/secrets/telegram_token
    stdin_open: true
    tty: true

  web:
    container_name: termin-web-dev
    image: rcheung/termin_base:0.0.1-1-DEV
    restart: always
    command: bash -c "npm install && /usr/bin/supervisord"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    secrets:
      - postgres_passwd
    ports:
      - 5678:4567/tcp
    environment:
      APP_ENV: development
      TZ: Europe/Berlin
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_passwd
      POSTGRES_USER: termin
    stdin_open: true
    tty: true

  db:
    container_name: termin-db-dev
    image: docker.io/library/postgres:16.0
    restart: always
    volumes:
      - ./var/postgresql_data:/var/lib/postgresql/data
    secrets:
      - postgres_passwd
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_passwd
      POSTGRES_USER: termin

  grid:
    container_name: termin-grid-dev
    image: docker.io/selenium/standalone-chrome:latest
    restart: always
    shm_size: 2gb
    ports:
      - 4445:4444/tcp
      - 7901:7900/tcp

secrets:
  postgres_passwd:
    file: ./secrets/postgres_passwd
  telegram_token:
    file: ./secrets/telegram_token
