services:
  termin:
    depends_on:
      - grid
    build:
      context: .
      dockerfile: Dockerfile-dev
      args:
        - RUBY_ENV=development
    volumes:
      - .:/usr/src/app
    command: bash -c "bundle install && ruby app.rb"
    environment:
      - RUBY_ENV=development
    stdin_open: true
    tty: true

  grid:
    image: docker.io/selenium/standalone-chrome:latest
    shm_size: '2gb'
    ports:
      - "4444:4444/tcp"
      - "7900:7900/tcp"
