services:
  runner:
    container_name: termin-runner
    image: rcheung/termin_base:0.0.1-1
    restart: always
    command: ruby app.rb
    depends_on:
      - grid
      - db
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_ENV=production
    volumes:
      - ./web/public/logs:/usr/src/app/web/public/logs:z
      - ./var/log_data:/usr/src/app/var/log_data:z
      - ./secrets/postgres_passwd:/run/secrets/postgres_passwd:z
      - ./secrets/telegram_token:/run/secrets/telegram_token:z
      - ./var/pid:/usr/src/app/var/pid:z
    environment:
      APP_ENV: production
      TZ: Europe/Berlin
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_passwd
      POSTGRES_USER: termin
      TELEGRAM_TOKEN_FILE: /run/secrets/telegram_token

  web:
    container_name: termin-web
    image: rcheung/termin_base:0.0.1-1
    command: ruby web.rb
    restart: always
    depends_on:
      - db
    volumes:
      - ./web/public/logs:/usr/src/app/web/public/logs:z
      - ./var/log_data:/usr/src/app/var/log_data:z
      - ./secrets/postgres_passwd:/run/secrets/postgres_passwd:z
      - ./var/pid:/usr/src/app/var/pid:z
    ports:
      - 4567:4567/tcp
    environment:
      APP_ENV: production
      TZ: Europe/Berlin
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_passwd
      POSTGRES_USER: termin

  db:
    container_name: termin-db
    image: docker.io/library/postgres:16.0
    restart: always
    volumes:
      - ./var/postgresql_data:/var/lib/postgresql/data:z
      - ./secrets/postgres_passwd:/run/secrets/postgres_passwd:z
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_passwd
      POSTGRES_USER: termin

  grid:
    container_name: termin-grid
    image: docker.io/selenium/standalone-chrome:latest
    restart: always
    shm_size: 2gb
    ports:
      - 4444:4444/tcp
      - 7900:7900/tcp
    environment:
      SE_OPTS: --session-timeout 600
