services:
  termin:
    depends_on:
      - grid
      - telegram
    build: ./termin
    command: ruby termin.rb

  telegram:
    build: ./telegram
    command: ruby telegram.rb
    ports:
      - "4567:4567/tcp"

  grid:
    image: docker.io/selenium/standalone-chrome:latest
    shm_size: '2gb'
    ports:
      - "4444:4444/tcp"
      - "7900:7900/tcp"
