services:
  termin:
    depends_on:
      - grid
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_ENV=production
    volumes:
      - "./data.db:/usr/src/app/data.db:Z"
      - "./data.db-shm:/usr/src/app/data.db-shm:Z"
      - "./data.db-wal:/usr/src/app/data.db-wal:Z"
      - "./lib/web/public/logs:/usr/src/app/lib/web/public/logs:z"
    environment:
      - APP_ENV=production
      - TZ=Europe/Berlin
    restart: always
    command: ruby app.rb

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_ENV=production
    volumes:
      - "./data.db:/usr/src/app/data.db:Z"
      - "./data.db-shm:/usr/src/app/data.db-shm:Z"
      - "./data.db-wal:/usr/src/app/data.db-wal:Z"
      - "./lib/web/public/logs:/usr/src/app/lib/web/public/logs:z"
    ports:
      - "4567:4567/tcp"
    command: ruby web.rb
    environment:
      - APP_ENV=production
      - TZ=Europe/Berlin

  grid:
    image: docker.io/selenium/standalone-chrome:latest
    restart: always
    shm_size: '2gb'
    ports:
      - "4444:4444/tcp"
      - "7900:7900/tcp"
