services:
  termin:
    depends_on:
      - grid
    build: .
    volumes:
      - "./data.db:/usr/src/app/data.db:Z"
    command: ruby app.rb

  grid:
    image: docker.io/selenium/standalone-chrome:latest
    shm_size: '2gb'
    ports:
      - "4444:4444/tcp"
      - "7900:7900/tcp"
