services:
  termin:
    depends_on:
      - grid
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - RUBY_ENV=production
    volumes:
      - "./data.db:/usr/src/app/data.db:Z"
    environment:
      - RUBY_ENV=production
    command: ruby app.rb

  grid:
    image: docker.io/selenium/standalone-chrome:latest
    shm_size: '2gb'
    ports:
      - "4444:4444/tcp"
      - "7900:7900/tcp"
